;
; File generated by cc65 v 2.18 - Debian 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_charout
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0003:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$00

.segment	"CODE"

	ldy     #$0C
	jsr     subysp
	ldy     #$0B
L0004:	lda     L0003,y
	sta     (sp),y
	dey
	bpl     L0004
	lda     sp
	ldx     sp+1
	jsr     pushax
	bra     L0008
L0006:	jsr     ldax0sp
	sta     regsave
	ina
	bne     L000C
	inx
L000C:	jsr     stax0sp
	lda     regsave
	jsr     _charout
L0008:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L0006
	tax
	ldy     #$0E
	jmp     addysp

.endproc

