;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_sprintf
	.export		_putstrnl
	.export		_main

.segment	"DATA"

_putstrnl:
	.word	$FFE8

.segment	"RODATA"

L0018:
	.byte	$25,$69,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$01
	jsr     pusha0
	jsr     pusha0
	jsr     push0
	ldy     #$0A
	jsr     subysp
	lda     #$00
	jsr     pusha
L0021:	sta     (sp)
	cmp     #$14
	bcs     L0020
	ldy     #$0E
	jsr     ldaxysp
	clc
	ldy     #$0F
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$0B
	jsr     staxysp
	ldy     #$0E
	jsr     ldaxysp
	ldy     #$0F
	jsr     staxysp
	ldy     #$0C
	jsr     ldaxysp
	ldy     #$0D
	jsr     staxysp
	lda     #$01
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0018)
	ldx     #>(L0018)
	jsr     pushax
	ldy     #$16
	jsr     pushwysp
	ldy     #$06
	jsr     _sprintf
	lda     _putstrnl
	ldx     _putstrnl+1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	lda     (sp)
	ina
	bra     L0021
L0020:	lda     #$00
	ldy     #$11
	jmp     addysp

.endproc

