import os
import pathlib
import subprocess

from harness import BCOS_ROM, EMU, ROOT, read_until, resolve_sd_image, spawn_emulator, stop_emulator


def test_more_supports_paging_and_binary_guard(tmp_path: pathlib.Path) -> None:
    assert BCOS_ROM.exists(), "BCOS ROM was not built"

    subprocess.run(
        ["bash", str(ROOT / "emulator" / "script" / "create_sd.sh")],
        cwd=ROOT,
        check=True,
    )
    sd_image = resolve_sd_image()
    assert sd_image.exists(), (
        "SD image not found. Create one with emulator/script/create_sd.sh "
        "or set BC6502_SDCARD_IMAGE."
    )

    test_sd = tmp_path / "sdcard-under-test.img"
    test_sd.write_bytes(sd_image.read_bytes())

    proc, master_fd = spawn_emulator(
        [
            str(EMU),
            "--board",
            "mini",
            "--rom",
            str(BCOS_ROM),
            "--sdcard",
            str(test_sd),
            "--clock",
            "12.0",
        ]
    )

    try:
        read_until(master_fd, ":/>", timeout_s=20.0)

        os.write(master_fd, b"more readme.txt\r")
        page_1 = read_until(master_fd, "--- SPACE: next page, Q: quit ---", timeout_s=10.0)
        assert "ByteCradle SD image generated by emulator/script/create_sd.sh" in page_1
        assert "Line 01" in page_1
        assert "Line 15" in page_1

        os.write(master_fd, b" ")
        page_2 = read_until(master_fd, "--- SPACE: next page, Q: quit ---", timeout_s=10.0)
        assert "Line 16" in page_2
        assert "Line 35" in page_2

        os.write(master_fd, b"q")
        read_until(master_fd, ":/>", timeout_s=10.0)

        os.write(master_fd, b"cd programs\r")
        read_until(master_fd, ":/PROGRAMS/>", timeout_s=10.0)

        os.write(master_fd, b"more hello.com\r")
        binary_output = read_until(master_fd, ":/PROGRAMS/>", timeout_s=10.0)
        assert "Binary file detected. Use HEXDUMP." in binary_output
    finally:
        stop_emulator(proc, master_fd)
