#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
IMAGE_NAME="$SCRIPT_DIR/sdcard.img"
PARTITION_SIZE_MIB=32
LABEL="BYTECRADLE"

echo "Creating an empty image file of size ${PARTITION_SIZE_MIB}MiB..."
truncate -s "$((PARTITION_SIZE_MIB * 1024 * 1024))" "$IMAGE_NAME"

echo "Partitioning the image..."
parted --script "$IMAGE_NAME" mklabel msdos
parted --script "$IMAGE_NAME" mkpart primary fat32 1MiB 100%

PART_START_SECTOR=$(parted -ms "$IMAGE_NAME" unit s print | awk -F: '/^1:/{gsub("s","",$2); print $2}')
if [ -z "$PART_START_SECTOR" ]; then
  echo "Failed to determine partition start sector" >&2
  exit 1
fi

PART_OFFSET_BYTES=$((PART_START_SECTOR * 512))

echo "Formatting partition (offset=${PART_OFFSET_BYTES} bytes) as FAT32..."
mkfs.fat -F 32 -n "$LABEL" --offset="$PART_START_SECTOR" "$IMAGE_NAME"

MTOOLS_IMAGE="${IMAGE_NAME}@@${PART_OFFSET_BYTES}"

echo "Populating FAT32 image via mtools..."
mmd -i "$MTOOLS_IMAGE" ::/PROGRAMS
mmd -i "$MTOOLS_IMAGE" ::/FOLDER1
mmd -i "$MTOOLS_IMAGE" ::/FOLDER2
mmd -i "$MTOOLS_IMAGE" ::/FOLDER1/SUB1
mmd -i "$MTOOLS_IMAGE" ::/FOLDER1/SUB2
mmd -i "$MTOOLS_IMAGE" ::/FOLDER2/SUB1
mmd -i "$MTOOLS_IMAGE" ::/FOLDER2/SUB2

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

cat > "$TMP_DIR/README.TXT" <<'EOF'
ByteCradle SD image generated by emulator/script/create_sd.sh

This README is intentionally multi-page so the MORE command paging
behavior can be exercised during emulator tests.

Line 01
Line 02
Line 03
Line 04
Line 05
Line 06
Line 07
Line 08
Line 09
Line 10
Line 11
Line 12
Line 13
Line 14
Line 15
Line 16
Line 17
Line 18
Line 19
Line 20
Line 21
Line 22
Line 23
Line 24
Line 25
Line 26
Line 27
Line 28
Line 29
Line 30
Line 31
Line 32
Line 33
Line 34
Line 35
Line 36
Line 37
Line 38
Line 39
Line 40
Line 41
Line 42
Line 43
Line 44
Line 45
EOF
cat > "$TMP_DIR/HELLO.TXT" <<'EOF'
Hello World!
EOF
: > "$TMP_DIR/EMPTY.TXT"
BIG_FILE="$TMP_DIR/BIG.TXT"
: > "$BIG_FILE"
for i in $(seq 0 599); do
    printf "\\$(printf '%03o' $((65 + (i % 26))))" >> "$BIG_FILE"
done
cat > "$TMP_DIR/FILE1.TXT" <<'EOF'
Sample file 1
EOF
cat > "$TMP_DIR/FILE2.TXT" <<'EOF'
Sample file 2
EOF

mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/README.TXT" ::/README.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/HELLO.TXT" ::/HELLO.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/EMPTY.TXT" ::/EMPTY.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/BIG.TXT" ::/BIG.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/FILE1.TXT" ::/FOLDER1/SUB1/FILE1.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/FILE2.TXT" ::/FOLDER1/SUB2/FILE2.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/FILE1.TXT" ::/FOLDER2/SUB1/FILE1.TXT
mcopy -i "$MTOOLS_IMAGE" "$TMP_DIR/FILE2.TXT" ::/FOLDER2/SUB2/FILE2.TXT

echo "Building programs..."
make -C "$ROOT_DIR/programs"

echo "Copying compiled programs..."
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/helloworld/HELLO.COM" ::/PROGRAMS/HELLO.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/diag/DIAG.COM" ::/PROGRAMS/DIAG.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/fibonacci/FIBO.COM" ::/PROGRAMS/FIBO.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/monitor/monitor.bin" ::/PROGRAMS/MONITOR.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/mandelbrot/MANDEL.COM" ::/PROGRAMS/MANDEL.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/argtest/ARGTEST.COM" ::/PROGRAMS/ARGTEST.COM
mcopy -i "$MTOOLS_IMAGE" "$ROOT_DIR/programs/fstest/FSTEST.COM" ::/PROGRAMS/FSTEST.COM

echo "SD card image creation completed: $IMAGE_NAME"
