#!/usr/bin/env python3
"""Generate monitor-local jump-table wrappers from BCOS jump-table spec."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
MON_DIR = ROOT / "programs/monitor"
BCOS_INC = ROOT / "src/jumptable.inc"

EXPORTS = ["putstr", "putstrnl", "putch", "newline", "puthex", "putdec", "getch"]


def parse_bcos_symbols(path: Path) -> dict[str, int]:
    assign = re.compile(r"^([A-Z0-9_]+)\s*=\s*(.+?)(?:\s*;.*)?$")
    values: dict[str, int] = {}

    def to_expr(expr: str) -> str:
        return expr.replace("$", "0x")

    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        m = assign.match(line)
        if not m:
            continue
        name, expr = m.groups()
        values[name] = eval(to_expr(expr), {"__builtins__": {}}, values)
    return values


def generate_inc(values: dict[str, int]) -> str:
    lines = [
        ";",
        "; Monitor jump-table mapping derived from BCOS jump-table spec.",
        "; Auto-generated by programs/monitor/generate_monitor_jumptable.py.",
        ";",
        "",
    ]
    keys = [
        "BCOS_JT_PUTSTR",
        "BCOS_JT_PUTSTRNL",
        "BCOS_JT_PUTCH",
        "BCOS_JT_NEWLINE",
        "BCOS_JT_PUTHEX",
        "BCOS_JT_PUTDEC",
        "BCOS_JT_GETCH",
    ]
    for k in keys:
        lines.append(f"{k:<18} = ${values[k]:04X}")
    lines.append("")
    return "\n".join(lines)


def generate_s() -> str:
    return """.include \"jumptable.inc\"

.export putstr
.export putstrnl
.export putch
.export newline
.export puthex
.export putdec
.export getch

putstr:
    jmp BCOS_JT_PUTSTR
putstrnl:
    jmp BCOS_JT_PUTSTRNL
putch:
    jmp BCOS_JT_PUTCH
newline:
    jmp BCOS_JT_NEWLINE
puthex:
    jmp BCOS_JT_PUTHEX
putdec:
    jmp BCOS_JT_PUTDEC
getch:
    jmp BCOS_JT_GETCH
"""


def write(path: Path, content: str) -> None:
    path.write_text(content)
    print(f"Wrote {path.relative_to(ROOT)}")


def main() -> None:
    values = parse_bcos_symbols(BCOS_INC)
    write(MON_DIR / "jumptable.inc", generate_inc(values))
    write(MON_DIR / "jumptable.s", generate_s())


if __name__ == "__main__":
    main()
