;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_sprintf
	.export		_main

.segment	"RODATA"

L0064:
	.byte	$42,$61,$6E,$6B,$20,$72,$61,$6E,$67,$65,$3A,$20,$24,$25,$30,$32
	.byte	$58,$2D,$24,$25,$30,$32,$58,$20,$28,$73,$61,$66,$65,$20,$6E,$6F
	.byte	$6E,$2D,$4F,$53,$20,$62,$61,$6E,$6B,$73,$29,$00
L006D:
	.byte	$50,$61,$74,$74,$65,$72,$6E,$73,$3A,$20,$41,$35,$5E,$6F,$66,$66
	.byte	$73,$65,$74,$5E,$62,$61,$6E,$6B,$2C,$20,$69,$6E,$76,$65,$72,$73
	.byte	$65,$2C,$20,$72,$65,$73,$74,$6F,$72,$65,$00
L0060:
	.byte	$54,$65,$73,$74,$69,$6E,$67,$20,$77,$72,$69,$74,$61,$62,$6C,$65
	.byte	$20,$62,$61,$6E,$6B,$65,$64,$20,$52,$41,$4D,$3A,$20,$24,$38,$30
	.byte	$30,$30,$2D,$24,$39,$46,$46,$46,$00
L00A9:
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$00
L0050:
	.byte	$3D,$3D,$3D,$20,$42,$59,$54,$45,$43,$52,$41,$44,$4C,$45,$20,$44
	.byte	$49,$41,$47,$4E,$4F,$53,$54,$49,$43,$53,$20,$28,$44,$49,$41,$47
	.byte	$29,$20,$3D,$3D,$3D,$00
L0054:
	.byte	$4D,$65,$6D,$6F,$72,$79,$20,$62,$61,$6E,$6B,$20,$74,$65,$73,$74
	.byte	$20,$28,$6E,$6F,$6E,$2D,$64,$65,$73,$74,$72,$75,$63,$74,$69,$76
	.byte	$65,$29,$2E,$00
L007A:
	.byte	$5B,$42,$41,$4E,$4B,$20,$25,$30,$32,$75,$2F,$24,$25,$30,$32,$58
	.byte	$5D,$20,$74,$65,$73,$74,$69,$6E,$67,$2E,$2E,$2E,$00
L008E:
	.byte	$46,$61,$69,$6C,$20,$62,$61,$6E,$6B,$3D,$24,$25,$30,$32,$58,$20
	.byte	$6F,$66,$66,$73,$65,$74,$3D,$24,$25,$30,$34,$58,$00
L0097:
	.byte	$45,$78,$70,$65,$63,$74,$65,$64,$3D,$24,$25,$30,$32,$58,$20,$41
	.byte	$63,$74,$75,$61,$6C,$3D,$24,$25,$30,$32,$58,$00
L00AD:
	.byte	$53,$55,$4D,$4D,$41,$52,$59,$3A,$20,$50,$41,$53,$53,$20,$28,$25
	.byte	$75,$2F,$25,$75,$20,$62,$61,$6E,$6B,$73,$29,$00
L00B6:
	.byte	$52,$41,$4D,$20,$62,$61,$6E,$6B,$20,$72,$65,$73,$74,$6F,$72,$65
	.byte	$64,$20,$74,$6F,$20,$24,$25,$30,$32,$58,$00
L0058:
	.byte	$49,$6E,$69,$74,$69,$61,$6C,$20,$52,$41,$4D,$20,$62,$61,$6E,$6B
	.byte	$3A,$20,$24,$25,$30,$32,$58,$00
L0048:
	.byte	$44,$49,$41,$47,$3A,$20,$41,$42,$49,$20,$6D,$69,$73,$6D,$61,$74
	.byte	$63,$68,$2E,$00
L008A:
	.byte	$52,$45,$53,$55,$4C,$54,$3A,$20,$46,$41,$49,$4C,$00
L00A2:
	.byte	$20,$2D,$3E,$20,$50,$41,$53,$53,$00

; ---------------------------------------------------------------
; unsigned char __near__ test_bank_non_destructive (unsigned char, __near__ struct $anon-struct-0001 *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_bank_non_destructive: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	sta     $7FC0
	ldx     #$80
	lda     #$00
	jsr     stax0sp
L0006:	ldy     #$01
	lda     (sp),y
	cmp     #$A0
	bne     L00C4
	lda     (sp)
	jeq     L0007
L00C4:	jsr     pushw0sp
	ldy     #$03
	jsr     ldaxysp
	sec
	sbc     #$00
	pha
	txa
	sbc     #$80
	tax
	pla
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	eor     #$A5
	sta     ptr1
	ldy     #$09
	lda     (sp),y
	eor     ptr1
	jsr     pusha
	lda     (sp)
	eor     #$FF
	jsr     pusha
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	sta     (ptr1)
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$01
	cmp     (sp),y
	beq     L0018
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (sp),y
	sta     (ptr1)
	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	jsr     ldaxysp
	ldy     #$01
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	ldy     #$03
	sta     (ptr1),y
	ldy     #$0C
	jsr     pushwysp
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$04
	jsr     staspidx
	ldx     #$00
	txa
	jsr     incsp7
	jmp     incsp5
L0018:	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     (sp)
	beq     L0025
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (sp),y
	sta     (ptr1)
	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	jsr     ldaxysp
	ldy     #$01
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$03
	sta     (ptr1),y
	ldy     #$0C
	jsr     pushwysp
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$04
	jsr     staspidx
	ldx     #$00
	txa
	jsr     incsp7
	jmp     incsp5
L0025:	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$02
	cmp     (sp),y
	beq     L0032
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$0B
	lda     (sp),y
	sta     (ptr1)
	dey
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	jsr     ldaxysp
	ldy     #$01
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	iny
	sta     (ptr1),y
	ldy     #$0C
	jsr     pushwysp
	ldy     #$08
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$04
	jsr     staspidx
	ldx     #$00
	txa
	jsr     incsp7
	jmp     incsp5
L0032:	jsr     incsp7
	lda     #$01
	jsr     addeq0sp
	jmp     L0006
L0007:	tax
	tya
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	lda     #$00
	jsr     pusha
	jsr     pusha
	ldy     #$46
	jsr     subysp
	ldx     #$FF
	lda     #$DC
	jsr     callax
	eor     #$01
	beq     L00C6
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L0048)
	ldx     #>(L0048)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	lda     #$01
	jmp     L003E
L00C6:	lda     $7FC0
	ldy     #$45
	sta     (sp),y
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L0050)
	ldx     #>(L0050)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L0054)
	ldx     #>(L0054)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0058)
	ldx     #>(L0058)
	jsr     pushax
	ldy     #$49
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L0060)
	ldx     #>(L0060)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0064)
	ldx     #>(L0064)
	jsr     pushax
	lda     #$04
	jsr     pusha0
	lda     #$3F
	jsr     pusha0
	ldy     #$08
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L006D)
	ldx     #>(L006D)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$04
	ldy     #$48
L00C5:	sta     (sp),y
	cmp     #$40
	jcs     L0070
	ldy     #$46
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L007A)
	ldx     #>(L007A)
	jsr     pushax
	ldy     #$4C
	lda     (sp),y
	jsr     pusha0
	ldy     #$4E
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$48
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     leaa0sp
	jsr     _test_bank_non_destructive
	cmp     #$00
	jne     L0081
	ldy     #$45
	lda     (sp),y
	sta     $7FC0
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L008A)
	ldx     #>(L008A)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L008E)
	ldx     #>(L008E)
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$0A
	jsr     pushwysp
	ldy     #$08
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0097)
	ldx     #>(L0097)
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	ldy     #$0A
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	lda     #$02
	jmp     L003E
L0081:	ldy     #$47
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L00A2)
	ldx     #>(L00A2)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$48
	clc
	lda     #$01
	adc     (sp),y
	jmp     L00C5
L0070:	ldy     #$45
	lda     (sp),y
	sta     $7FC0
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L00A9)
	ldx     #>(L00A9)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L00AD)
	ldx     #>(L00AD)
	jsr     pushax
	ldy     #$4B
	lda     (sp),y
	jsr     pusha0
	ldy     #$4C
	lda     (sp),y
	jsr     pusha0
	ldy     #$08
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L00B6)
	ldx     #>(L00B6)
	jsr     pushax
	ldy     #$49
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	txa
L003E:	ldy     #$49
	jmp     addysp

.endproc

