;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_main
	.export		_callmain

; ---------------------------------------------------------------
; int __near__ callmain (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_callmain: near

.segment	"CODE"

	lda     $0600
	jsr     pusha0
	ldx     #$06
	lda     #$01
	jmp     _main

.endproc

