;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_sprintf
	.export		_main

.segment	"RODATA"

L0011:
	.byte	$41,$52,$47,$43,$3D,$00
L0020:
	.byte	$41,$52,$47,$56,$5B,$00
L0024:
	.byte	$25,$75,$00
L002C:
	.byte	$5D,$3D,$00
L000C	:=	L0024+0

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	lda     $0600
	jsr     pusha
	ldx     #$06
	lda     #$01
	jsr     pushax
	jsr     decsp8
	ldx     #$FF
	lda     #$DC
	jsr     callax
	eor     #$01
	beq     L0005
	ldx     #$00
	lda     #$01
	jmp     L0001
L0005:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L000C)
	ldx     #>(L000C)
	jsr     pushax
	ldy     #$0E
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L0011)
	ldx     #>(L0011)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$00
	ldy     #$0B
L0037:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$0C
	lda     (sp),y
	jsr     tosicmp0
	jcs     L0017
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L0020)
	ldx     #>(L0020)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0024)
	ldx     #>(L0024)
	jsr     pushax
	ldy     #$0F
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L002C)
	ldx     #>(L002C)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	inx
	ldy     #$0D
	lda     (sp),y
	asl     a
	bcc     L0034
	inx
	clc
L0034:	ldy     #$0A
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     ldaxi
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$0B
	lda     (sp),y
	ina
	jmp     L0037
L0017:	ldx     #$00
	txa
L0001:	ldy     #$0C
	jmp     addysp

.endproc

