;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_sprintf
	.export		_main

.segment	"RODATA"

L0012:
	.byte	$41,$52,$47,$43,$3D,$00
L0021:
	.byte	$41,$52,$47,$56,$5B,$00
L0025:
	.byte	$25,$75,$00
L002D:
	.byte	$5D,$3D,$00
L000D	:=	L0025+0

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	lda     $0600
	jsr     pusha
	ldx     #$06
	lda     #$01
	jsr     pushax
	jsr     decsp8
	ldx     #$FF
	lda     #$DC
	jsr     callax
	eor     #$01
	beq     L0006
	ldx     #$00
	lda     #$01
	jmp     L0002
L0006:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L000D)
	ldx     #>(L000D)
	jsr     pushax
	ldy     #$0E
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L0012)
	ldx     #>(L0012)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$00
	ldy     #$0B
L0038:	sta     (sp),y
	lda     (sp),y
	jsr     pusha0
	ldy     #$0C
	lda     (sp),y
	jsr     tosicmp0
	jcs     L0018
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L0021)
	ldx     #>(L0021)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0025)
	ldx     #>(L0025)
	jsr     pushax
	ldy     #$0F
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _sprintf
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	lda     #<(L002D)
	ldx     #>(L002D)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	inx
	ldy     #$0D
	lda     (sp),y
	asl     a
	bcc     L0035
	inx
	clc
L0035:	ldy     #$0A
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     ldaxi
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$0B
	lda     (sp),y
	ina
	jmp     L0038
L0018:	ldx     #$00
	txa
L0002:	ldy     #$0C
	jmp     addysp

.endproc

