;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_memcmp
	.export		_main

.segment	"RODATA"

L009D:
	.byte	$42,$79,$74,$65,$43,$72,$61,$64,$6C,$65,$20,$53,$44,$20,$69,$6D
	.byte	$61,$67,$65,$20,$67,$65,$6E,$65,$72,$61,$74,$65,$64,$20,$62,$00
L006D	:=	L009D+0
L031D:
	.byte	$6F,$70,$65,$6E,$2D,$72,$65,$61,$64,$6F,$6E,$6C,$79,$2D,$66,$6F
	.byte	$72,$2D,$77,$72,$69,$74,$65,$00
L00B1:
	.byte	$62,$6C,$6F,$63,$6B,$2D,$61,$64,$76,$61,$6E,$63,$65,$2D,$73,$74
	.byte	$61,$74,$75,$73,$00
L0378:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$63,$72,$65,$61,$74,$65,$2D,$66
	.byte	$6C,$75,$73,$68,$00
L036F:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$63,$72,$65,$61,$74,$65,$2D,$77
	.byte	$72,$69,$74,$65,$00
L00B9:
	.byte	$79,$20,$65,$6D,$75,$6C,$61,$74,$6F,$72,$2F,$73,$63,$72,$69,$70
	.byte	$74,$2F,$63,$72,$00
L03E5:
	.byte	$73,$74,$61,$74,$2D,$70,$72,$6F,$67,$72,$61,$6D,$73,$2D,$64,$69
	.byte	$72,$00
L0402:
	.byte	$72,$65,$61,$64,$64,$69,$72,$2D,$7A,$65,$72,$6F,$2D,$64,$61,$74
	.byte	$61,$00
L0080:
	.byte	$6F,$70,$65,$6E,$2D,$72,$65,$61,$64,$6D,$65,$2D,$62,$6C,$6F,$63
	.byte	$6B,$00
L023C:
	.byte	$72,$65,$61,$64,$2D,$62,$6C,$6F,$63,$6B,$2D,$62,$61,$64,$2D,$66
	.byte	$64,$00
L01DC:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$62,$61,$64,$2D,$6E,$61,$6D,$65
	.byte	$00
L01EF:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$62,$61,$64,$2D,$6D,$6F,$64,$65
	.byte	$00
L0346:
	.byte	$77,$72,$69,$74,$65,$2D,$62,$6C,$6F,$63,$6B,$2D,$6E,$75,$6C,$6C
	.byte	$00
L022A:
	.byte	$72,$65,$61,$64,$2D,$62,$79,$74,$65,$2D,$62,$61,$64,$2D,$66,$64
	.byte	$00
L03D2:
	.byte	$73,$74,$61,$74,$2D,$72,$65,$61,$64,$6D,$65,$2D,$64,$61,$74,$61
	.byte	$00
L0414:
	.byte	$72,$65,$73,$74,$6F,$72,$65,$2D,$70,$72,$6F,$67,$72,$61,$6D,$73
	.byte	$00
L0305:
	.byte	$63,$72,$65,$61,$74,$65,$2D,$64,$75,$70,$6C,$69,$63,$61,$74,$65
	.byte	$00
L0106:
	.byte	$72,$65,$61,$64,$2D,$61,$66,$74,$65,$72,$2D,$63,$6C,$6F,$73,$65
	.byte	$00
L029B:
	.byte	$63,$72,$65,$61,$74,$65,$2D,$6D,$75,$6C,$74,$69,$70,$6C,$65,$00
L02A6:
	.byte	$63,$72,$65,$61,$74,$65,$2D,$62,$61,$64,$2D,$6E,$61,$6D,$65,$00
L0070:
	.byte	$72,$65,$61,$64,$2D,$73,$65,$71,$75,$65,$6E,$74,$69,$61,$6C,$00
L01C9:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$6D,$69,$73,$73,$69,$6E,$67,$00
L00F9:
	.byte	$6F,$70,$65,$6E,$2D,$63,$6C,$6F,$73,$65,$2D,$72,$65,$61,$64,$00
L0245:
	.byte	$72,$65,$61,$64,$2D,$62,$6C,$6F,$63,$6B,$2D,$6E,$75,$6C,$6C,$00
L0427:
	.byte	$67,$65,$74,$63,$77,$64,$2D,$70,$72,$6F,$67,$72,$61,$6D,$73,$00
L021B:
	.byte	$63,$68,$64,$69,$72,$2D,$62,$61,$64,$2D,$6E,$61,$6D,$65,$00
L03BA:
	.byte	$76,$65,$72,$69,$66,$79,$2D,$77,$72,$69,$74,$74,$65,$6E,$00
L0358:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$63,$72,$65,$61,$74,$65,$00
L033C:
	.byte	$66,$6C,$75,$73,$68,$2D,$72,$65,$61,$64,$6F,$6E,$6C,$79,$00
L0333:
	.byte	$77,$72,$69,$74,$65,$2D,$72,$65,$61,$64,$6F,$6E,$6C,$79,$00
L00E4:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$68,$61,$75,$73,$74,$65,$64,$00
L00BC:
	.byte	$62,$6C,$6F,$63,$6B,$2D,$61,$64,$76,$61,$6E,$63,$65,$00
L0223:
	.byte	$6F,$70,$65,$6E,$2D,$62,$61,$64,$2D,$6E,$61,$6D,$65,$00
L03DF:
	.byte	$73,$74,$61,$74,$2D,$70,$72,$6F,$67,$72,$61,$6D,$73,$00
L0213:
	.byte	$63,$68,$64,$69,$72,$2D,$6D,$69,$73,$73,$69,$6E,$67,$00
L0251:
	.byte	$73,$74,$61,$74,$2D,$62,$61,$64,$2D,$6E,$61,$6D,$65,$00
L0424:
	.byte	$3A,$2F,$50,$52,$4F,$47,$52,$41,$4D,$53,$2F,$3E,$20,$00
L01B0:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$72,$65,$61,$64,$00
L03AA:
	.byte	$72,$65,$61,$64,$2D,$77,$72,$69,$74,$74,$65,$6E,$00
L0388:
	.byte	$73,$74,$61,$74,$2D,$77,$72,$69,$74,$74,$65,$6E,$00
L01CD:
	.byte	$42,$41,$44,$2A,$4E,$41,$4D,$45,$2E,$54,$58,$54,$00
L019E:
	.byte	$6F,$70,$65,$6E,$2D,$6D,$69,$73,$73,$69,$6E,$67,$00
L013B:
	.byte	$62,$69,$67,$2D,$62,$6F,$75,$6E,$64,$61,$72,$79,$00
L0312:
	.byte	$66,$6C,$75,$73,$68,$2D,$62,$61,$64,$2D,$66,$64,$00
L01F7:
	.byte	$6F,$70,$65,$6E,$2D,$65,$78,$2D,$6E,$75,$6C,$6C,$00
L0204:
	.byte	$67,$65,$74,$63,$77,$64,$2D,$73,$6D,$61,$6C,$6C,$00
L02EE:
	.byte	$77,$72,$69,$74,$65,$2D,$73,$65,$63,$6F,$6E,$64,$00
L02B7	:=	L036F+8
L0095:
	.byte	$62,$6C,$6F,$63,$6B,$2D,$73,$74,$61,$74,$75,$73,$00
L03FB:
	.byte	$72,$65,$61,$64,$64,$69,$72,$2D,$7A,$65,$72,$6F,$00
L02A0	:=	L01CD+0
L0221	:=	L01CD+0
L0267:
	.byte	$63,$6C,$6F,$73,$65,$2D,$62,$61,$64,$2D,$66,$64,$00
L025F:
	.byte	$72,$65,$61,$64,$64,$69,$72,$2D,$6E,$75,$6C,$6C,$00
L03F2:
	.byte	$73,$74,$61,$74,$2D,$6D,$69,$73,$73,$69,$6E,$67,$00
L0248	:=	L01CD+0
L0394:
	.byte	$6F,$70,$65,$6E,$2D,$77,$72,$69,$74,$74,$65,$6E,$00
L0044:
	.byte	$67,$65,$74,$63,$77,$64,$2D,$72,$6F,$6F,$74,$00
L014F:
	.byte	$62,$69,$67,$2D,$61,$64,$76,$61,$6E,$63,$65,$00
L03CA:
	.byte	$73,$74,$61,$74,$2D,$72,$65,$61,$64,$6D,$65,$00
L0051:
	.byte	$6F,$70,$65,$6E,$2D,$72,$65,$61,$64,$6D,$65,$00
L02F7:
	.byte	$77,$72,$69,$74,$65,$2D,$66,$6C,$75,$73,$68,$00
L018E:
	.byte	$62,$6C,$6F,$63,$6B,$2D,$65,$6D,$70,$74,$79,$00
L020B:
	.byte	$67,$65,$74,$63,$77,$64,$2D,$6E,$75,$6C,$6C,$00
L0431:
	.byte	$46,$53,$54,$45,$53,$54,$20,$46,$41,$49,$4C,$00
L040C:
	.byte	$72,$65,$61,$64,$64,$69,$72,$2D,$65,$6F,$66,$00
L02DC:
	.byte	$77,$72,$69,$74,$65,$2D,$66,$69,$72,$73,$74,$00
L042E:
	.byte	$46,$53,$54,$45,$53,$54,$20,$50,$41,$53,$53,$00
L00A0:
	.byte	$62,$6C,$6F,$63,$6B,$2D,$72,$65,$61,$64,$00
L0031:
	.byte	$63,$68,$64,$69,$72,$2D,$72,$6F,$6F,$74,$00
L007A:
	.byte	$52,$45,$41,$44,$4D,$45,$2E,$54,$58,$54,$00
L00DE	:=	L007A+0
L0317	:=	L007A+0
L017A:
	.byte	$72,$65,$61,$64,$2D,$65,$6D,$70,$74,$79,$00
L00D9:
	.byte	$6D,$75,$6C,$74,$69,$2D,$6F,$70,$65,$6E,$00
L03E9:
	.byte	$4E,$4F,$46,$49,$4C,$45,$2E,$54,$58,$54,$00
L004B	:=	L007A+0
L0349:
	.byte	$4F,$50,$45,$4E,$45,$58,$2E,$54,$58,$54,$00
L01E0	:=	L007A+0
L00D0	:=	L007A+0
L0198	:=	L03E9+0
L03C1	:=	L007A+0
L00F3	:=	L007A+0
L01BA	:=	L03E9+0
L016E:
	.byte	$6F,$70,$65,$6E,$2D,$65,$6D,$70,$74,$79,$00
L01A1	:=	L007A+0
L0168:
	.byte	$45,$4D,$50,$54,$59,$2E,$54,$58,$54,$00
L037E:
	.byte	$57,$52,$36,$30,$30,$2E,$54,$58,$54,$00
L0258:
	.byte	$73,$74,$61,$74,$2D,$6E,$75,$6C,$6C,$00
L02FF	:=	L037E+0
L02B1	:=	L037E+0
L038E	:=	L037E+0
L03D6:
	.byte	$50,$52,$4F,$47,$52,$41,$4D,$53,$00
L0412	:=	L03D6+0
L0127:
	.byte	$62,$69,$67,$2D,$72,$65,$61,$64,$00
L0219:
	.byte	$42,$41,$44,$2A,$4E,$41,$4D,$45,$00
L0028:
	.byte	$46,$41,$49,$4C,$20,$61,$62,$69,$00
L0211:
	.byte	$4E,$4F,$46,$4F,$4C,$44,$45,$52,$00
L0111:
	.byte	$6F,$70,$65,$6E,$2D,$62,$69,$67,$00
L015E:
	.byte	$62,$69,$67,$2D,$65,$6F,$66,$00
L010B:
	.byte	$42,$49,$47,$2E,$54,$58,$54,$00
L0009:
	.byte	$46,$41,$49,$4C,$20,$00
L0006:
	.byte	$50,$41,$53,$53,$20,$00
L0041:
	.byte	$3A,$2F,$3E,$20,$00
L002F:
	.byte	$2F,$00

; ---------------------------------------------------------------
; unsigned char __near__ check (unsigned char, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check: near

.segment	"CODE"

	jsr     pushax
	ldx     #$FF
	lda     #$E5
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	beq     L0007
	lda     #<(L0006)
	ldx     #>(L0006)
	bra     L000A
L0007:	lda     #<(L0009)
	ldx     #>(L0009)
L000A:	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$02
	lda     (sp),y
	beq     L0010
	ldx     #$00
	txa
	jmp     incsp3
L0010:	ina
	ldx     #$00
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ expected_big_byte (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_expected_big_byte: near

.segment	"CODE"

	jsr     pushax
	jsr     pushw0sp
	lda     #$1A
	jsr     tosumoda0
	ldy     #$41
	jsr     incaxy
	ldx     #$00
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ expected_write_byte (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_expected_write_byte: near

.segment	"CODE"

	jsr     pushax
	jsr     pushw0sp
	lda     #$1A
	jsr     tosumoda0
	ldy     #$61
	jsr     incaxy
	ldx     #$00
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L0020:
	.res	610,$00

.segment	"CODE"

	ldy     #$9E
	jsr     subysp
	lda     #$00
	jsr     pusha
	ldx     #$FF
	lda     #$DC
	jsr     callax
	eor     #$01
	beq     L0022
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	lda     #<(L0028)
	ldx     #>(L0028)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	jmp     L043A
L0022:	ldx     #$FF
	lda     #$B8
	jsr     pushax
	lda     #<(L002F)
	ldx     #>(L002F)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L0031)
	ldx     #>(L0031)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$3A
	jsr     leaa0sp
	ldy     #$06
	jsr     staxysp
	lda     #$60
	ldy     #$08
	sta     (sp),y
	lda     #$FF
	iny
	sta     (sp),y
	tax
	lda     #$BB
	jsr     pushax
	lda     #$08
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L003F
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0041)
	ldx     #>(L0041)
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     _memcmp
	cpx     #$00
	bne     L003F
	cmp     #$00
	beq     L003C
L003F:	lda     #$00
	bra     L043B
L003C:	ina
L043B:	jsr     pusha
	lda     #<(L0044)
	ldx     #>(L0044)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L004B)
	ldx     #>(L004B)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L0051)
	ldx     #>(L0051)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L0053
	lda     #$00
	ldy     #$39
L046D:	sta     (sp),y
	cmp     #$1F
	bcs     L043F
	ldx     #$FF
	lda     #$C4
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$35
	jsr     staxysp
	lda     #$3A
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$35
	lda     (sp),y
	pha
	ldy     #$39
	lda     (sp),y
	tay
	pla
	sta     (ptr1),y
	ldy     #$36
	jsr     ldaxysp
	cpx     #$80
	bcs     L0057
	ldy     #$39
	lda     (sp),y
	ina
	bra     L046D
L0057:	ldy     #$39
L043F:	lda     (sp),y
	cmp     #$1F
	bne     L0440
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L006D)
	ldx     #>(L006D)
	jsr     pushax
	ldx     #$00
	lda     #$1F
	jsr     _memcmp
	cpx     #$00
	bne     L0440
	cmp     #$00
	beq     L006A
L0440:	lda     #$00
	bra     L0441
L006A:	ina
L0441:	jsr     pusha
	lda     #<(L0070)
	ldx     #>(L0070)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0053:	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L007A)
	ldx     #>(L007A)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L0080)
	ldx     #>(L0080)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L0082
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #$3A
	jsr     leaa0sp
	iny
	jsr     staxysp
	ldx     #$00
	lda     #$1F
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L0095)
	ldx     #>(L0095)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$33
	lda     (sp),y
	bne     L0442
	dey
	lda     (sp),y
	cmp     #$1F
	bne     L0442
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L009D)
	ldx     #>(L009D)
	jsr     pushax
	ldx     #$00
	lda     #$1F
	jsr     _memcmp
	cpx     #$00
	bne     L0442
	cmp     #$00
	beq     L0099
L0442:	lda     #$00
	bra     L0443
L0099:	ina
L0443:	jsr     pusha
	lda     #<(L00A0)
	ldx     #>(L00A0)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$3A
	jsr     leaa0sp
	ldy     #$2E
	jsr     staxysp
	ldx     #$00
	lda     #$14
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L00B1)
	ldx     #>(L00B1)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$33
	lda     (sp),y
	bne     L0444
	dey
	lda     (sp),y
	cmp     #$14
	bne     L0444
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L00B9)
	ldx     #>(L00B9)
	jsr     pushax
	ldx     #$00
	lda     #$14
	jsr     _memcmp
	cpx     #$00
	bne     L0444
	cmp     #$00
	beq     L00B5
L0444:	lda     #$00
	bra     L0445
L00B5:	ina
L0445:	jsr     pusha
	lda     #<(L00BC)
	ldx     #>(L00BC)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0082:	lda     #$00
	ldy     #$39
L046E:	sta     (sp),y
	cmp     #$04
	bcs     L0449
	lda     #$9A
	jsr     leaa0sp
	clc
	adc     (sp),y
	bcc     L00CD
	inx
L00CD:	jsr     pushax
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L00D0)
	ldx     #>(L00D0)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$00
	jsr     staspidx
	lda     #$9A
	jsr     leaa0sp
	ldy     #$39
	clc
	adc     (sp),y
	bcc     L00D5
	inx
L00D5:	ldy     #$00
	jsr     ldaidx
	asl     a
	bcs     L00C4
	ldy     #$39
	lda     (sp),y
	ina
	bra     L046E
L00C4:	ldy     #$39
L0449:	lda     (sp),y
	cmp     #$04
	jsr     booleq
	jsr     pusha
	lda     #<(L00D9)
	ldx     #>(L00D9)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L00DE)
	ldx     #>(L00DE)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	asl     a
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L00E4)
	ldx     #>(L00E4)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	bra     L00E8
L044B:	lda     (sp),y
	sec
	sbc     #$01
	sta     (sp),y
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	lda     #$9C
	jsr     leaa0sp
	ldy     #$3B
	clc
	adc     (sp),y
	bcc     L00EF
	inx
L00EF:	ldy     #$00
	jsr     ldaidx
	pha
	lda     (sp)
	sta     jmpvec+1
	iny
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L00E8:	ldy     #$39
	lda     (sp),y
	bne     L044B
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L00F3)
	ldx     #>(L00F3)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L00F9)
	ldx     #>(L00F9)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	bmi     L00FB
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$FF
	lda     #$C4
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cpx     #$80
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L0106)
	ldx     #>(L0106)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
L00FB:	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L010B)
	ldx     #>(L010B)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L0111)
	ldx     #>(L0111)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L0113
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #<(L0020)
	ldx     #>(L0020)
	iny
	jsr     staxysp
	ldx     #$02
	lda     #$08
	ldy     #$30
	jsr     staxysp
	ldx     #$00
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L0126
	ldy     #$33
	lda     (sp),y
	cmp     #$02
	bne     L0126
	dey
	lda     (sp),y
	cmp     #$08
	beq     L0123
L0126:	lda     #$00
	bra     L044C
L0123:	lda     #$01
L044C:	jsr     pusha
	lda     #<(L0127)
	ldx     #>(L0127)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     L0020
	jsr     pusha0
	lda     #$00
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0130
	lda     L0020+25
	jsr     pusha0
	lda     #$19
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0130
	lda     L0020+26
	jsr     pusha0
	lda     #$1A
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0130
	lda     L0020+511
	jsr     pusha0
	ldx     #$01
	lda     #$FF
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0130
	lda     L0020+512
	jsr     pusha0
	ldx     #$02
	lda     #$00
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0130
	lda     L0020+519
	jsr     pusha0
	ldx     #$02
	lda     #$07
	jsr     _expected_big_byte
	jsr     tosicmp
	beq     L012D
L0130:	lda     #$00
	bra     L044D
L012D:	lda     #$01
L044D:	jsr     pusha
	lda     #<(L013B)
	ldx     #>(L013B)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$00
	lda     #$50
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L0149
	ldy     #$33
	lda     (sp),y
	bne     L0149
	dey
	lda     (sp),y
	cmp     #$50
	bne     L0149
	lda     L0020
	jsr     pusha0
	ldx     #$02
	lda     #$08
	jsr     _expected_big_byte
	jsr     tosicmp
	bne     L0149
	lda     L0020+79
	jsr     pusha0
	ldx     #$02
	lda     #$57
	jsr     _expected_big_byte
	jsr     tosicmp
	beq     L0146
L0149:	lda     #$00
	bra     L044E
L0146:	lda     #$01
L044E:	jsr     pusha
	lda     #<(L014F)
	ldx     #>(L014F)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$00
	lda     #$01
	ldy     #$30
	jsr     staxysp
	ldy     #$32
	jsr     staxysp
	txa
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FB
	bne     L015D
	ldy     #$32
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L015A
L015D:	lda     #$00
	bra     L044F
L015A:	ina
L044F:	jsr     pusha
	lda     #<(L015E)
	ldx     #>(L015E)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0113:	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L0168)
	ldx     #>(L0168)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L016E)
	ldx     #>(L016E)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L0170
	ldx     #$FF
	lda     #$C4
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$35
	jsr     staxysp
	cpx     #$80
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L017A)
	ldx     #>(L017A)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #$3A
	jsr     leaa0sp
	iny
	jsr     staxysp
	ldx     #$00
	lda     #$60
	ldy     #$30
	jsr     staxysp
	lda     #$01
	ldy     #$32
	jsr     staxysp
	txa
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FB
	bne     L018D
	ldy     #$32
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L018A
L018D:	lda     #$00
	bra     L0450
L018A:	ina
L0450:	jsr     pusha
	lda     #<(L018E)
	ldx     #>(L018E)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0170:	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L0198)
	ldx     #>(L0198)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	asl     a
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L019E)
	ldx     #>(L019E)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L01A1)
	ldx     #>(L01A1)
	ldy     #$01
	jsr     staxysp
	lda     #$01
	ldy     #$03
	sta     (sp),y
	lda     #$FF
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	tax
	lda     #$C1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L01AE
	ldy     #$04
	lda     (sp),y
	tax
	bpl     L01AB
L01AE:	lda     #$00
	bra     L0451
L01AB:	lda     #$01
L0451:	jsr     pusha
	lda     #<(L01B0)
	ldx     #>(L01B0)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$04
	lda     (sp),y
	tax
	bmi     L01B3
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L01B3:	lda     #<(L01BA)
	ldx     #>(L01BA)
	ldy     #$01
	jsr     staxysp
	lda     #$01
	ldy     #$03
	sta     (sp),y
	iny
	sta     (sp),y
	dea
	iny
	sta     (sp),y
	ldx     #$FF
	lda     #$C1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FE
	bne     L01C7
	ldy     #$04
	lda     (sp),y
	asl     a
	bcs     L0452
L01C7:	lda     #$00
	bra     L0453
L0452:	lda     #$01
L0453:	jsr     pusha
	lda     #<(L01C9)
	ldx     #>(L01C9)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L01CD)
	ldx     #>(L01CD)
	ldy     #$01
	jsr     staxysp
	lda     #$01
	ldy     #$03
	sta     (sp),y
	iny
	sta     (sp),y
	dea
	iny
	sta     (sp),y
	ldx     #$FF
	lda     #$C1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FC
	bne     L01DA
	ldy     #$04
	lda     (sp),y
	asl     a
	bcs     L0454
L01DA:	lda     #$00
	bra     L0455
L0454:	lda     #$01
L0455:	jsr     pusha
	lda     #<(L01DC)
	ldx     #>(L01DC)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L01E0)
	ldx     #>(L01E0)
	ldy     #$01
	jsr     staxysp
	lda     #$7F
	ldy     #$03
	sta     (sp),y
	lda     #$01
	iny
	sta     (sp),y
	dea
	iny
	sta     (sp),y
	ldx     #$FF
	lda     #$C1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	bne     L01ED
	ldy     #$04
	lda     (sp),y
	asl     a
	bcs     L0456
L01ED:	lda     #$00
	bra     L0457
L0456:	lda     #$01
L0457:	jsr     pusha
	lda     #<(L01EF)
	ldx     #>(L01EF)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$C1
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L01F7)
	ldx     #>(L01F7)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$3A
	jsr     leaa0sp
	ldy     #$06
	jsr     staxysp
	lda     #$02
	ldy     #$08
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	ldx     #$FF
	lda     #$BB
	jsr     pushax
	lda     #$08
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L0204)
	ldx     #>(L0204)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BB
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L020B)
	ldx     #>(L020B)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$B8
	jsr     pushax
	lda     #<(L0211)
	ldx     #>(L0211)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     boolne
	jsr     pusha
	lda     #<(L0213)
	ldx     #>(L0213)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$B8
	jsr     pushax
	lda     #<(L0219)
	ldx     #>(L0219)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     boolne
	jsr     pusha
	lda     #<(L021B)
	ldx     #>(L021B)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L0221)
	ldx     #>(L0221)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	asl     a
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L0223)
	ldx     #>(L0223)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$C4
	jsr     pushax
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cpx     #$80
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L022A)
	ldx     #>(L022A)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$FF
	ldy     #$2D
	sta     (sp),y
	lda     #$3A
	jsr     leaa0sp
	iny
	jsr     staxysp
	ldx     #$00
	lda     #$01
	ldy     #$30
	jsr     staxysp
	lda     #$7B
	ldy     #$32
	jsr     staxysp
	txa
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FB
	bne     L023B
	ldy     #$32
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L0238
L023B:	lda     #$00
	bra     L0458
L0238:	ina
L0458:	jsr     pusha
	lda     #<(L023C)
	ldx     #>(L023C)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$C7
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L0245)
	ldx     #>(L0245)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L0248)
	ldx     #>(L0248)
	ldy     #$21
	jsr     staxysp
	lda     #$00
	ldy     #$2C
	sta     (sp),y
	ldx     #$FF
	lda     #$CA
	jsr     pushax
	lda     #$23
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FC
	jsr     booleq
	jsr     pusha
	lda     #<(L0251)
	ldx     #>(L0251)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$CA
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L0258)
	ldx     #>(L0258)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$CD
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L025F)
	ldx     #>(L025F)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	lda     #$01
	jsr     pusha
	lda     #<(L0267)
	ldx     #>(L0267)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$00
	ldy     #$39
L046F:	sta     (sp),y
	cmp     #$04
	jcs     L045C
	lda     #$44
	iny
	sta     (sp),y
	lda     #$47
	iny
	sta     (sp),y
	ldy     #$39
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosudiva0
	ldy     #$30
	jsr     incaxy
	ldy     #$3C
	sta     (sp),y
	ldy     #$39
	lda     (sp),y
	jsr     pusha0
	lda     #$0A
	jsr     tosumoda0
	ldy     #$30
	jsr     incaxy
	ldy     #$3D
	sta     (sp),y
	lda     #$2E
	iny
	sta     (sp),y
	lda     #$54
	iny
	sta     (sp),y
	lda     #$58
	iny
	sta     (sp),y
	lda     #$54
	iny
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
	ldx     #$FF
	lda     #$D0
	jsr     pushax
	lda     #$3C
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	asl     a
	bcs     L026A
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$39
	lda     (sp),y
	ina
	jmp     L046F
L026A:	ldy     #$39
L045C:	lda     (sp),y
	cmp     #$04
	jsr     booleq
	jsr     pusha
	lda     #<(L029B)
	ldx     #>(L029B)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D0
	jsr     pushax
	lda     #<(L02A0)
	ldx     #>(L02A0)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	asl     a
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L02A6)
	ldx     #>(L02A6)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	bmi     L02A8
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L02A8:	ldx     #$FF
	lda     #$D0
	jsr     pushax
	lda     #<(L02B1)
	ldx     #>(L02B1)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L02B7)
	ldx     #>(L02B7)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L02B9
	ldx     #$00
	txa
L0472:	ldy     #$37
	jsr     staxysp
	ldy     #$38
	lda     (sp),y
	cmp     #$02
	bne     L02C4
	dey
	lda     (sp),y
	cmp     #$62
L02C4:	bcs     L02BD
	lda     #<(L0020)
	ldy     #$37
	clc
	adc     (sp),y
	pha
	lda     #>(L0020)
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$3A
	jsr     ldaxysp
	jsr     _expected_write_byte
	ldy     #$00
	jsr     staspidx
	ldy     #$38
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	ina
	bne     L0472
	inx
	bra     L0472
L02BD:	ldy     #$9E
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #<(L0020)
	ldx     #>(L0020)
	iny
	jsr     staxysp
	ldx     #$02
	lda     #$08
	ldy     #$30
	jsr     staxysp
	ldx     #$00
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$D3
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L02DB
	ldy     #$33
	lda     (sp),y
	cmp     #$02
	bne     L02DB
	dey
	lda     (sp),y
	cmp     #$08
	beq     L02D8
L02DB:	lda     #$00
	bra     L045D
L02D8:	lda     #$01
L045D:	jsr     pusha
	lda     #<(L02DC)
	ldx     #>(L02DC)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L0020+520)
	ldx     #>(L0020+520)
	ldy     #$2E
	jsr     staxysp
	ldx     #$00
	lda     #$50
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$D3
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L02ED
	ldy     #$33
	lda     (sp),y
	bne     L02ED
	dey
	lda     (sp),y
	cmp     #$50
	beq     L02EA
L02ED:	lda     #$00
	bra     L045E
L02EA:	lda     #$01
L045E:	jsr     pusha
	lda     #<(L02EE)
	ldx     #>(L02EE)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D6
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L02F7)
	ldx     #>(L02F7)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L02B9:	ldx     #$FF
	lda     #$D0
	jsr     pushax
	lda     #<(L02FF)
	ldx     #>(L02FF)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	asl     a
	lda     #$00
	rol     a
	jsr     pusha
	lda     #<(L0305)
	ldx     #>(L0305)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	bmi     L0307
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0307:	ldx     #$FF
	lda     #$D6
	jsr     pushax
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FA
	jsr     booleq
	jsr     pusha
	lda     #<(L0312)
	ldx     #>(L0312)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L0317)
	ldx     #>(L0317)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L031D)
	ldx     #>(L031D)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L031F
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #<(L0020)
	ldx     #>(L0020)
	iny
	jsr     staxysp
	ldx     #$00
	lda     #$01
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$D3
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	beq     L045F
	ldy     #$32
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L032F
	lda     #$00
	bra     L045F
L032F:	ina
L045F:	jsr     pusha
	lda     #<(L0333)
	ldx     #>(L0333)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D6
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L033C)
	ldx     #>(L033C)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L031F:	ldx     #$FF
	lda     #$D3
	jsr     pushax
	inx
	txa
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FF
	jsr     booleq
	jsr     pusha
	lda     #<(L0346)
	ldx     #>(L0346)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L0349)
	ldx     #>(L0349)
	ldy     #$01
	jsr     staxysp
	lda     #$02
	ldy     #$03
	sta     (sp),y
	lda     #$FF
	iny
	sta     (sp),y
	iny
	sta     (sp),y
	tax
	lda     #$C1
	jsr     pushax
	lda     #$03
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L0356
	ldy     #$04
	lda     (sp),y
	tax
	bpl     L0353
L0356:	lda     #$00
	bra     L0460
L0353:	lda     #$01
L0460:	jsr     pusha
	lda     #<(L0358)
	ldx     #>(L0358)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$04
	lda     (sp),y
	tax
	jmi     L035B
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #<(L0020)
	ldx     #>(L0020)
	iny
	jsr     staxysp
	ldx     #$00
	lda     #$0D
	ldy     #$30
	jsr     staxysp
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$D3
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L036E
	ldy     #$33
	lda     (sp),y
	bne     L036E
	dey
	lda     (sp),y
	cmp     #$0D
	beq     L036B
L036E:	lda     #$00
	bra     L0461
L036B:	lda     #$01
L0461:	jsr     pusha
	lda     #<(L036F)
	ldx     #>(L036F)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D6
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L0378)
	ldx     #>(L0378)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$06
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L035B:	lda     #<(L037E)
	ldx     #>(L037E)
	ldy     #$21
	jsr     staxysp
	lda     #$FF
	ldy     #$2C
	sta     (sp),y
	tax
	lda     #$CA
	jsr     pushax
	lda     #$23
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L0387
	ldy     #$27
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$02
	stz     sreg
	stz     sreg+1
	lda     #$58
	jsr     toseqeax
	bne     L0384
L0387:	lda     #$00
	bra     L0462
L0384:	lda     #$01
L0462:	jsr     pusha
	lda     #<(L0388)
	ldx     #>(L0388)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$BE
	jsr     pushax
	lda     #<(L038E)
	ldx     #>(L038E)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldy     #$9E
	sta     (sp),y
	tax
	jsr     boolge
	jsr     pusha
	lda     #<(L0394)
	ldx     #>(L0394)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$9E
	lda     (sp),y
	tax
	jmi     L0396
	lda     (sp),y
	ldy     #$2D
	sta     (sp),y
	lda     #<(L0020)
	ldx     #>(L0020)
	iny
	jsr     staxysp
	ldx     #$02
	lda     #$58
	ldy     #$30
	jsr     staxysp
	ldx     #$00
	txa
	ldy     #$32
	jsr     staxysp
	dea
	ldy     #$34
	sta     (sp),y
	dex
	lda     #$C7
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L03A9
	ldy     #$33
	lda     (sp),y
	cmp     #$02
	bne     L03A9
	dey
	lda     (sp),y
	cmp     #$58
	beq     L03A6
L03A9:	lda     #$00
	bra     L0463
L03A6:	lda     #$01
L0463:	jsr     pusha
	lda     #<(L03AA)
	ldx     #>(L03AA)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     L0020
	jsr     pusha0
	lda     #$00
	jsr     _expected_write_byte
	jsr     tosicmp
	bne     L03B3
	lda     L0020+511
	jsr     pusha0
	ldx     #$01
	lda     #$FF
	jsr     _expected_write_byte
	jsr     tosicmp
	bne     L03B3
	lda     L0020+512
	jsr     pusha0
	ldx     #$02
	lda     #$00
	jsr     _expected_write_byte
	jsr     tosicmp
	bne     L03B3
	lda     L0020+599
	jsr     pusha0
	ldx     #$02
	lda     #$57
	jsr     _expected_write_byte
	jsr     tosicmp
	beq     L03B0
L03B3:	lda     #$00
	bra     L0464
L03B0:	lda     #$01
L0464:	jsr     pusha
	lda     #<(L03BA)
	ldx     #>(L03BA)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$D9
	jsr     pushax
	ldy     #$A0
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
L0396:	lda     #<(L03C1)
	ldx     #>(L03C1)
	ldy     #$21
	jsr     staxysp
	lda     #$FF
	ldy     #$2C
	sta     (sp),y
	tax
	lda     #$CA
	jsr     pushax
	lda     #$23
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L03CA)
	ldx     #>(L03CA)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$23
	lda     (sp),y
	and     #$10
	bne     L0465
	ldy     #$27
	jsr     ldeaxysp
	cmp     #$29
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L0466
L0465:	lda     #$00
	bra     L0467
L0466:	lda     #$01
L0467:	jsr     pusha
	lda     #<(L03D2)
	ldx     #>(L03D2)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L03D6)
	ldx     #>(L03D6)
	ldy     #$21
	jsr     staxysp
	lda     #$FF
	ldy     #$2C
	sta     (sp),y
	tax
	lda     #$CA
	jsr     pushax
	lda     #$23
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L03DF)
	ldx     #>(L03DF)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$23
	lda     (sp),y
	and     #$10
	jsr     boolne
	jsr     pusha
	lda     #<(L03E5)
	ldx     #>(L03E5)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #<(L03E9)
	ldx     #>(L03E9)
	ldy     #$21
	jsr     staxysp
	lda     #$00
	ldy     #$2C
	sta     (sp),y
	ldx     #$FF
	lda     #$CA
	jsr     pushax
	lda     #$23
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FE
	jsr     booleq
	jsr     pusha
	lda     #<(L03F2)
	ldx     #>(L03F2)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$00
	ldy     #$0A
	sta     (sp),y
	ldx     #$FF
	lda     #$CD
	jsr     pushax
	lda     #$0C
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L03FB)
	ldx     #>(L03FB)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldy     #$0B
	lda     (sp),y
	beq     L046B
	ldy     #$1F
	jsr     ldeaxysp
	cmp     #$02
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L046A
	lda     #$00
	bra     L046B
L046A:	lda     #$01
L046B:	jsr     pusha
	lda     #<(L0402)
	ldx     #>(L0402)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$FA
	ldy     #$0A
	sta     (sp),y
	ldx     #$FF
	lda     #$CD
	jsr     pushax
	lda     #$0C
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$FB
	jsr     booleq
	jsr     pusha
	lda     #<(L040C)
	ldx     #>(L040C)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$B8
	jsr     pushax
	lda     #<(L0412)
	ldx     #>(L0412)
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	jsr     booleq
	jsr     pusha
	lda     #<(L0414)
	ldx     #>(L0414)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	lda     #$3A
	jsr     leaa0sp
	ldy     #$06
	jsr     staxysp
	lda     #$60
	ldy     #$08
	sta     (sp),y
	lda     #$FF
	iny
	sta     (sp),y
	tax
	lda     #$BB
	jsr     pushax
	lda     #$08
	jsr     leaa0sp
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	cmp     #$00
	bne     L0422
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	lda     #<(L0424)
	ldx     #>(L0424)
	jsr     pushax
	ldx     #$00
	lda     #$0D
	jsr     _memcmp
	cpx     #$00
	bne     L0422
	cmp     #$00
	beq     L041F
L0422:	lda     #$00
	bra     L046C
L041F:	ina
L046C:	jsr     pusha
	lda     #<(L0427)
	ldx     #>(L0427)
	jsr     _check
	clc
	adc     (sp)
	sta     (sp)
	ldx     #$FF
	lda     #$E8
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	bne     L042F
	lda     #<(L042E)
	ldx     #>(L042E)
	bra     L0432
L042F:	lda     #<(L0431)
	ldx     #>(L0431)
L0432:	pha
	lda     (sp)
	sta     jmpvec+1
	dey
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	ldx     #$00
	lda     (sp)
	beq     L001C
L043A:	lda     #$01
L001C:	ldy     #$9F
	jmp     addysp

.endproc

