#!/usr/bin/env python3
"""Generate BCOS jump-table artifacts from one table definition.

Generated files:
- src/jumptable.inc
- src/jumptable.s
- src/sbc.cfg
- programs/.generated/io.h
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ABI_MAJOR = 1
ABI_MINOR = 0
VECTOR_START = 0xFFFA
STRIDE = 3

# Single source of truth for entry ordering and implementation targets.
# Keep stable public API entries at their legacy addresses.
ENTRIES = [
    ("BCOS_JT_ABI_MAJOR", "bcos_get_abi_major"),
    ("BCOS_JT_ABI_MINOR", "bcos_get_abi_minor"),
    ("BCOS_JT_RESERVED0", "bcos_reserved"),
    ("BCOS_JT_PUTSTR", "putstr"),
    ("BCOS_JT_PUTSTRNL", "putstrnl"),
    ("BCOS_JT_PUTCH", "putch"),
    ("BCOS_JT_NEWLINE", "newline"),
    ("BCOS_JT_PUTHEX", "puthex"),
    ("BCOS_JT_PUTDEC", "putdec"),
    ("BCOS_JT_GETCH", "getch"),
]

JT_COUNT = len(ENTRIES)
JT_BASE = VECTOR_START - (JT_COUNT * STRIDE)


def write(path: Path, content: str) -> None:
    path.write_text(content)
    print(f"Wrote {path.relative_to(ROOT)}")


def generate_inc() -> str:
    lines = [
        ";",
        "; ByteCradle OS jump table layout.",
        "; Auto-generated by src/generate_bcos_artifacts.py.",
        ";",
        "",
        f"BCOS_ABI_MAJOR = {ABI_MAJOR}",
        f"BCOS_ABI_MINOR = {ABI_MINOR}",
        "",
        f"BCOS_JT_BASE         = ${JT_BASE:04X}",
        f"BCOS_JT_STRIDE       = {STRIDE}",
    ]

    for idx, (name, _) in enumerate(ENTRIES):
        addr = JT_BASE + (idx * STRIDE)
        lines.append(f"{name:<20} = BCOS_JT_BASE + ({idx} * BCOS_JT_STRIDE) ; ${addr:04X}")

    lines += [
        "",
        f"BCOS_JT_COUNT        = {JT_COUNT}",
        "BCOS_JT_END          = BCOS_JT_BASE + (BCOS_JT_COUNT * BCOS_JT_STRIDE)",
        f"BCOS_VECTOR_START    = ${VECTOR_START:04X}",
        "",
    ]
    return "\n".join(lines)


def generate_jumptable_s() -> str:
    lines = [
        ";",
        "; ByteCradle OS Jump Table",
        "; Auto-generated by src/generate_bcos_artifacts.py.",
        ";",
        "",
        '.include "functions.inc"',
        '.include "jumptable.inc"',
        "",
        '.segment "JUMPTABLE"',
        "",
        "jumptable:",
    ]

    for idx, (name, target) in enumerate(ENTRIES):
        addr = JT_BASE + (idx * STRIDE)
        lines.append(f"    jmp {target:<18} ; {name} (${addr:04X})")

    lines += [
        "",
        '.assert * = BCOS_VECTOR_START, error, "Jump table size mismatch: update entry list"',
        "",
    ]
    return "\n".join(lines)


def generate_sbc_cfg() -> str:
    return f"""MEMORY {{
    ZP:     start = $20,   size = $40,   type = rw, define = yes;
    RAM:    start = $0300, size = $0500, define = yes;
    ROM:    start = $C000, size = $4000, fill = $00, type = ro;
    BANK2:  start = $A000, size = $2000, fill = $00, type = ro;
}}

SEGMENTS {{
    ZEROPAGE:  load = ZP,  type = zp,  define   = yes;
    DATA:      load = ROM, type = rw,  define   = yes, run = RAM;
    BSS:       load = RAM, type = bss, define   = yes;
    HEAP:      load = RAM, type = bss, optional = yes;
    STARTUP:   load = ROM, type = ro;
    ONCE:      load = ROM, type = ro,  optional = yes;
    CODE:      load = ROM, type = ro;
    RODATA:    load = ROM, type = ro;
    B2CODE:    load = BANK2, type = ro;
    B2RODATA:  load = BANK2, type = ro;
    JUMPTABLE: load = ROM, type=ro,    start= ${JT_BASE:04X};
    VECTORS:   load = ROM, type = ro,  start    = ${VECTOR_START:04X};
}}

FEATURES {{
    CONDES:    segment = STARTUP,
               type    = constructor,
               label   = __CONSTRUCTOR_TABLE__,
               count   = __CONSTRUCTOR_COUNT__;
    CONDES:    segment = STARTUP,
               type    = destructor,
               label   = __DESTRUCTOR_TABLE__,
               count   = __DESTRUCTOR_COUNT__;
}}

SYMBOLS {{
    # Define the stack size for the application
    __STACKSIZE__:  value = $0100, type = weak;
}}
"""


def generate_c_header() -> str:
    names = {name: JT_BASE + i * STRIDE for i, (name, _) in enumerate(ENTRIES)}
    return f"""#ifndef BCOS_IO_H
#define BCOS_IO_H

/* Auto-generated by src/generate_bcos_artifacts.py. */
#include <stdint.h>

#define BCOS_ABI_MAJOR    {ABI_MAJOR}u
#define BCOS_ABI_MINOR    {ABI_MINOR}u

#define BCOS_JT_BASE      0x{JT_BASE:04X}u
#define BCOS_JT_STRIDE    {STRIDE}u
#define BCOS_JT_ABI_MAJOR 0x{names['BCOS_JT_ABI_MAJOR']:04X}u
#define BCOS_JT_ABI_MINOR 0x{names['BCOS_JT_ABI_MINOR']:04X}u
#define BCOS_JT_PUTSTR    0x{names['BCOS_JT_PUTSTR']:04X}u
#define BCOS_JT_PUTSTRNL  0x{names['BCOS_JT_PUTSTRNL']:04X}u
#define BCOS_JT_PUTCH     0x{names['BCOS_JT_PUTCH']:04X}u
#define BCOS_JT_NEWLINE   0x{names['BCOS_JT_NEWLINE']:04X}u
#define BCOS_JT_PUTHEX    0x{names['BCOS_JT_PUTHEX']:04X}u
#define BCOS_JT_PUTDEC    0x{names['BCOS_JT_PUTDEC']:04X}u
#define BCOS_JT_GETCH     0x{names['BCOS_JT_GETCH']:04X}u

#define bcos_abi_major ((uint8_t (*)(void))BCOS_JT_ABI_MAJOR)
#define bcos_abi_minor ((uint8_t (*)(void))BCOS_JT_ABI_MINOR)
#define putstr         ((void (*)(const uint8_t*))BCOS_JT_PUTSTR)
#define putstrnl       ((void (*)(const uint8_t*))BCOS_JT_PUTSTRNL)
#define putch          ((void (*)(uint8_t))BCOS_JT_PUTCH)

#define BCOS_ABI_COMPATIBLE() ((bcos_abi_major() == BCOS_ABI_MAJOR) && (bcos_abi_minor() >= BCOS_ABI_MINOR))

#endif
"""


def main() -> None:
    write(ROOT / "src/jumptable.inc", generate_inc())
    write(ROOT / "src/jumptable.s", generate_jumptable_s())
    write(ROOT / "src/sbc.cfg", generate_sbc_cfg())

    out = ROOT / "programs/.generated/io.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    write(out, generate_c_header())


if __name__ == "__main__":
    main()
