;
; Defines all functions available in all .s files
;

.import isr
.import newline
.import newcmdline
.import putstr
.import putstrnl
.import char2num
.import char2nibble
.import chartoupper
.import _puthex
.import puthex
.import putdec
.import putspace
.import putds
.import puttab
.import printnibble
.import _putch
.import putch
.import _getch
.import getpos
.import ischarvalid
.import clearline
.import makecrctable
