;
; Defines all functions available in all .s files
;

.import isr
.import newline
.import putstr
.import putstrnl
.import char2num
.import char2nibble
.import chartoupper
.import getch
.import putch
.import puthex
.import putdec
.import putdecword
.import putspace
.import putds
.import puttab
.import printnibble
.import getpos
.import ischarvalid
.import clearline
.import strlen
.import putrepch
